name: all-dev-helloworld

base: core24

version: '1.0.0'

grade: stable
confinement: strict


# --- METADATA FIELDS ---
license: Proprietary
title: A chello world snap for ALL
contact: s.yebbare@all.is.one
website: https://all.is.one/
issues: https://github.com/allisonesnap/snap_all-dev-helloworld/issues
source-code: https://github.com/allisonesnap/snap_all-dev-helloworld
donation: https://github.com/allisonesnap/snap_all-dev-helloworld/donation
# ---------------------------------


summary: Hello World application for ALL360 OS

description: |
  A simple Hello World application demonstrating
  strict confinement, runtime configuration,
  configuration hooks and persistent application data
  on ALL360 OS.

apps:
  hello-all360:
    command: scripts/hello-all360

parts:
  hello-all360:
    plugin: dump
    source: .
    stage:
      - scripts/hello-all360
